import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import SSRComponent from '@/Components/SSRComponent';
import CSRComponent from '@/Components/CSRComponent';
import { GetServerSideProps } from 'next';

const inter = Inter({ subsets: ['latin'] });

interface HomeProps {
  ssrData: string;
}

export const getServerSideProps: GetServerSideProps = async () => {
  // Simulate data fetching
  const ssrData = 'SSR Component: Data Loaded';

  return {
    props: {
      ssrData,
    },
  };
};

export default function Home({ ssrData }: HomeProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
        </div>

        <SSRComponent data={ssrData} />
        <CSRComponent />
      </main>
    </>
  );
}
